# Generated by Django 5.0.7 on 2024-07-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('phone', models.CharField(default='1234', max_length=12)),
                ('email', models.CharField(blank=True, default='exapmple@gmail.com', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('phone', models.CharField(default='1234', max_length=12)),
                ('email', models.CharField(blank=True, default='exapmple@gmail.com', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
