# Generated by Django 5.0.7 on 2024-07-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default='+91 12345678910', max_length=14, null=True),
        ),
    ]
