# Generated by Django 5.0.6 on 2024-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='availability',
            field=models.DurationField(default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
