# Generated by Django 5.0.6 on 2024-07-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_appoinment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, default='exapmple@gmail.com', max_length=40),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Prefer Not to say', max_length=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='1234', max_length=12),
        ),
    ]
