# Generated by Django 5.0.6 on 2024-08-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_nurse_pharmacist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Sc', 'Scheduled'), ('Co', 'Completed'), ('Ca', 'Cancelled')], max_length=2, null=True),
        ),
    ]
