# Generated by Django 5.0.6 on 2024-08-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_status_rename_choices_choice_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.DurationField(default=None),
        ),
    ]
