# Generated by Django 5.0.6 on 2024-07-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_doctor_specialization_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialization',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='message',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(blank=True, default='exapmple@gmail.com', max_length=40),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='1234', max_length=12),
        ),
    ]
