# Generated by Django 5.0.6 on 2024-07-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_rename_specialization_department_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoinment',
            new_name='Appointment',
        ),
    ]
